### ISSUE TITLE
TX - Add AddValidators Bundled Signature to Frontend

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/frontend#1]
Enable the use of `AddValidators` bundled signature method to streamline minipool creation and reduce the number of user signatures.

**Comment by frankmchugh** [comment]
Have made it all the way to a 400 error from the API, so everything for the most part is in place. The error message I am getting in the error is "Invalid data: invalid encoded type". I read over the srv.js code and have seen that it throws this error when the struct type is wrong... But as you can see from my code below, the Struct Type is "AddValidators". I am sure we will be able to work this out next time Ramana and I are both available...



const handleAddValidator = async () => {


    if (address !== undefined) {

      let browserProvider = new ethers.BrowserProvider((window as any).ethereum)
      let signer = await browserProvider.getSigner()
      const storageContract = new ethers.Contract(storageAddress, storageABI, signer);
      const distributorAddress = await storageContract["getAddress(bytes32)"](ethers.id("contract.addressrocketNodeDistributorFactory"))
      const distributorContract = new ethers.Contract(distributorAddress, distributorABI, signer);


      const feeRecipient = await distributorContract.getProxyAddress(address);
      const date = Math.floor(Date.now() / 1000);



      const EIP712Domain = { name: "vrün", version: "1", chainId: currentChain };



      const types = {
        "AddValidators": [
          { name: "timestamp", type: "uint256" },
          { name: "firstIndex", type: "uint256" },
          { name: "amountGwei", type: "uint256" },
          { name: "feeRecipient", type: "address" },
          { name: "graffiti", type: "string" },
          { name: "withdrawalAddresses", type: "address[]" },
        ]
      }


      const value = {

        timestamp: date.toString(),
        firstIndex: "0",
        amountGwei: parseEther(minipoolDepositInput).toString(),
        feeRecipient: feeRecipient.toLowerCase(),
        graffiti: grafittiInput,
        withdrawalAddresses: [address.toLowerCase()]

      }


      const APIType = "AddValidators";
      let signature = await signer.signTypedData(EIP712Domain, types, value);


      await fetch(`https://db.vrün.com/${currentChain}/${address}/0`, {
        method: "POST",

        headers: {
          "Content-Type": "application/json"
        },

        body: JSON.stringify({
          type: APIType,
          data: value,
          signature: signature
        })
      })
        .then(async response => {

          var jsonString = await response.json()
          console.log("Result of AddValidators" + jsonString)
        })
        .catch(error => {

          console.log(error);
        });
    }
  }

**Comment by xrchz** [comment]
This was a bug in the server, should be addressed by https://github.com/stakevrun/db/commit/5178e011e1cf2561ad43c082812e10a9144f29cb
