### ISSUE TITLE
Deposit Data invalid signature

### ISSUE THREAD

**Issue by frankmchugh** [stakevrun/frontend#10]
https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa#code is the code that is checking the deposit data root, and https://github.com/stakevrun/db/blob/main/srv.js#L217 is our code creating deposit data. So there's some discrepancy between those two I'm gonna try to track down.

**Comment by xrchz** [comment]
https://github.com/stakevrun/db/commit/37fcf759df4c5afe0a7252bd32fcf4d4097911e2 might fix this

**Comment by xrchz** [comment]
The deposit data root as verified by the deposit contract is correct now, I think, but the signed data and signature are invalid (as checked by the beacon chain). So I'm gonna try to debug that now.

**Comment by xrchz** [comment]
I think this should be solved by https://github.com/stakevrun/db/commit/e5526eba99f8ac35aff87b9d3a249d726a1928ab

**Comment by xrchz** [comment]
Still broken, we're up to here now https://github.com/paulmillr/noble-curves/issues/128

**Comment by xrchz** [comment]
Solved in https://github.com/stakevrun/db/commit/3c9434fedaf2797e0994e31204a92a7a7d8d7340
