### ISSUE TITLE
TX - Create Minipool Exit Process

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/frontend#13]
#### Description
Users need the ability to exit their validators via our ui. 

#### Objectives
- Users have the ability exit specific validators / minipools

#### Requirements
- UI elements to exit validator
- Create exit transaction
- Method to check the position of minipool in exit queue
- Method to distribute and claim eth and rewards from exited validator

**Comment by xrchz** [comment]
Let's also use this to recover the Holesky ETH locked in https://holesky.etherscan.io/address/0x1e81010d133e5907de1195f1c4346c24f9d19963

**Comment by frankmchugh** [comment]
This has been done, but need to triple check the Error handling of the Post Presigned Exit message
