### ISSUE TITLE
Update landing page copy

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/frontend#2]
The landing page only has placeholder copy and does not explain our service to new users. 

**Objectives:**
- Enhance clarity around our service's benefits and features.
- Increase user engagement and conversion rate by improving the copy's appeal.

**Tasks:**
1. Review the current landing page content.
2. Draft new copy that includes:
   - A clear, concise value proposition statement.
   - Descriptions of key features and benefits.
   - A compelling call to action (CTA) that guides users to the next step (e.g., "Start Staking Now").
3. Implement the new copy on the website.

**Comment by frankmchugh** [comment]
Done
