### ISSUE TITLE
Create pricing page

### ISSUE THREAD

**Issue by xrchz** [stakevrun/frontend#346]
Add a page to the website that details how we charge for running validators.

How we charge should be (probably isn't yet) written up in the docs repo, but a rough summary now:
- We charge per day (and per validator) that a validator is running (and enabled by the user). A partial day is rounded up to 1 day.
- Users accumulate fees in the form of "days charged".
- Users can pay us fees in multiple currencies including at least ETH and USDC.
- We set a "price per day" in each of these currencies, which is subject to change (with notice).
- Users must prepay. If they are charged a day and don't have any prepaid funds to settle it, we may disable their validator(s).

The initial prices per day are probably in the ballpark of 0.3 USDC and 0.00005 ETH, but these need to be confirmed/decided...

**Comment by bpietroniro** [comment]
Are you interested in having a "calculate your fees and/or revenue" section on the pricing page? Something akin to
<img width="300" alt="Screen Shot 2024-07-16 at 21 35 11" src="https://github.com/user-attachments/assets/82f3179d-4562-48ed-83b6-2dfc31bafb62">

**Comment by bpietroniro** [comment]
I think the pricing page is (minimally) ready for content, modeled after the FAQ page.

One lingering question—there's some code in the FAQ page involving setting state with the user's account and chain ID. Wondering whether we need this there or in Pricing; I'm not certain what it's there for on these essentially static pages, but I could be overlooking something

**Comment by xrchz** [comment]
I think the static pages should not require the account and chain ID, and removing those requirements from them is probably good if possible. I haven't looked in detail if there's something on those pages that actually requires the account and chain id to be known.

**Comment by xrchz** [comment]
> Are you interested in having a "calculate your fees and/or revenue" section on the pricing page? Something akin to https://www.rainforestpay.com/pricing/ in terms of UI

This could be cool! As a P1 or P2 issue (i.e. not _required_ for launch).

**Comment by xrchz** [comment]
Did you make a pull request or commit with the minimal content pricing page already? (Maybe mention this issue there if so)
