### ISSUE TITLE
UI - Add Darkmode and Toggle

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/frontend#37]
# Implement Dark Mode with Toggle

## Description

Implement a Dark Mode feature with a toggle switch, allowing users to choose between light and dark themes. 

## Objectives

- Enable Dark Mode functionality.
- Remember user's theme preference across sessions.

## Requirements

 - https://www.rainbowkit.com/docs/theming

### UI

- Add a Dark Mode toggle switch in a visible location.

### Design

- Ensure readability and visibility for all elements in both themes.
- Adapt all charts and visual aids for Dark Mode.

### Technical

- Use CSS variables or CSS-in-JS for theme management. (maybe?)
- Store user's theme preference locally.
- Ensure cross-device and cross-browser compatibility.

## Benefits

- Enhances user experience by providing a customizable interface.
- Improves accessibility and reduces eye strain in low-light conditions.

**Comment by frankmchugh** [comment]
I have a very decent Dark Mode in place and have chosen a Dark mode theme from the RainbowKit for the wallet interactions. Unsure of the best way to know Account Preferences for the toggling, but would be interested to explore that in more depth at a later stage of the process. Will  create a new issue in P1 or P2
